### ISSUE TITLE
Error: Host not found

### ISSUE THREAD

**Issue by xlqstar** [inconshreveable/slt#2]
when i connect it,show me this:

slt 2015/02/03 23:16:57 server.go:104: Failed to mux connection from 183.206.192.151:32656, error: Host not found:

i can't understand what happened.

**Comment by inconshreveable** [comment]
This can happen if your client doesn't set the SNI extension data in the TLS connection. Older browsers and some proxies don't populate the field. Wikipedia gives a very good summary of well-behaved clients: https://en.wikipedia.org/wiki/Server_Name_Indication#Implementation
